# Generated by Django 5.2.12 on 2026-04-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_posts_filename_posts_original_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
    ]
